#pragma once

#define VIAL_KEYBOARD_UID {0x89, 0x36, 0x2A, 0xC7, 0xFA, 0xD8, 0x89, 0x45}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
//#define VIAL_UNLOCK_COMBO_ROWS {4, 4}
#define VIAL_UNLOCK_COMBO_COLS {1, 2}
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 3000
